- name:  "go-sf"
  link:  "https://msbu-tech.github.io/go-sf/"
  intro: "Service 框架生成工具"
- name:  "msbu-tech.github.io"
  link:  "https://github.com/msbu-tech/msbu-tech.github.io"
  intro: "MSBU Tech GitHub 首页"