- name:  "go-sf"
  link:  "https://github.com/msbu-tech/go-sf"
  intro: "Service Framework generator in Go"
- name:  "msbu-tech.github.io"
  link:  "https://github.com/msbu-tech/msbu-tech.github.io"
  intro: "MSBU Tech on GitHub"
- name:  "Wunder Cafe"
  link:  "https://github.com/msbu-tech/wundercafe"
  intro: "Sync Wunderlist with New iCafe and control via task comment."