- name:  "msbu-tech.github.io"
  link:  "https://github.com/msbu-tech/msbu-tech.github.io"
  repo:  "msbu-tech/msbu-tech.github.io"
  intro: "MSBU Tech GitHub 首页"
- name:  "go-sf"
  link:  "https://msbu-tech.github.io/go-sf/"
  repo:  "msbu-tech/go-sf"
  intro: "Service 框架生成工具"
- name:  "pysvn-jumbo-repo"
  link:  "https://github.com/msbu-tech/pysvn-jumbo-repo"
  repo:  "msbu-tech/pysvn-jumbo-repo"
  intro: "pysvn jumbo 包"
